routes:
- name: Trivy Operator Alerts
  input: input.report.summary.criticalCount > 0
  actions: [tag-vulnerable-k8s]
  template: trivy-raw-json

# Templates are used to format a message
templates:
- name: trivy-raw-json
  rego-package: postee.rawmessage.json

# Actions are target services that should consume the messages
actions:
- name: tag-vulnerable-k8s
  type: kubernetes
  enable: true
  kube-namespace: "default"
  kube-config-file: "~/.kube/config"
  kube-label-selector: "app=nginx"
  kube-actions:
    labels:
      vulnerable: "true"